const $=id=>document.getElementById(id);let current=[],currentRows=[],rawText="",customMap={},priorHistory={};
let rules={tolerance:0.02,maxTaxRate:30,allowedCurrencies:["USD","EUR","GBP","UZS","KZT","AED"]};
try{rules={...rules,...JSON.parse(localStorage.getItem("invoiceguard_rules")||"{}")}}catch{}
function syncRuleInputs(){$("tolerance").value=rules.tolerance;$("maxTaxRate").value=rules.maxTaxRate;$("allowedCurrencies").value=(rules.allowedCurrencies||[]).join(",")}

const aliases={invoice_number:["invoice_number","invoice_no","invoice_#","invoice","bill_number","bill_no","reference","reference_number"],vendor:["vendor","supplier","supplier_name","vendor_name","payee","contact"],date:["date","invoice_date","bill_date","transaction_date"],subtotal:["subtotal","sub_total","net","net_amount","amount_ex_tax","amount_before_tax"],tax:["tax","vat","gst","tax_amount","vat_amount","gst_amount"],total:["total","amount","total_amount","gross","gross_amount","amount_due"],currency:["currency","currency_code","ccy"]};
const normalize=s=>String(s||"").trim().toLowerCase().replace(/[^a-z0-9#]+/g,"_").replace(/^_|_$/g,"");
const normalizeDuplicatePart=s=>String(s||"").normalize("NFKC").trim().toLocaleLowerCase().replace(/[^\p{L}\p{N}]+/gu,"");
const duplicateKey=(vendor,no)=>normalizeDuplicatePart(vendor)+"|"+normalizeDuplicatePart(no);
function canonical(h){const n=normalize(h);if(customMap[n])return customMap[n];for(const [key,list] of Object.entries(aliases))if(list.includes(n))return key;return n}
function parseCSV(text){const lines=text.trim().split(/\r?\n/);if(lines.length<2)return[];const split=line=>{let out=[],v="",q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){v+='"';i++;}else if(c==='"')q=!q;else if(c===','&&!q){out.push(v.trim());v="";}else v+=c}out.push(v.trim());return out};const raw=split(lines[0]),h=raw.map(canonical);$("mapping").textContent=raw.map((x,i)=>x+" → "+h[i]).join(" · ");showUnknown(raw,h);return lines.slice(1).filter(Boolean).map((l,i)=>Object.fromEntries(split(l).map((v,j)=>[h[j]||"col"+j,v]).concat([["_row",i+2]])))}
function showUnknown(raw,h){const known=new Set(Object.keys(aliases));const unknown=raw.map((name,i)=>({name,key:h[i],norm:normalize(name)})).filter(x=>!known.has(x.key));const panel=$("mappingPanel"),fields=$("mappingFields");if(!unknown.length){panel.classList.add("hidden");fields.innerHTML="";return}panel.classList.remove("hidden");const opts='<option value="">Ignore</option>'+Object.keys(aliases).map(k=>'<option value="'+k+'">'+k.replaceAll("_"," ")+'</option>').join("");fields.innerHTML=unknown.map(x=>'<label>'+esc(x.name)+'<select data-col="'+esc(x.norm)+'">'+opts+'</select></label>').join("")}
function num(v){const s=String(v??"").trim();if(!s)return NaN;let cleaned=s.replace(/[^0-9,.-]/g,"");if(cleaned.includes(",")&&!cleaned.includes("."))cleaned=cleaned.replace(",",".");else cleaned=cleaned.replace(/,/g,"");return Number(cleaned)}
function history(){try{return JSON.parse(localStorage.getItem("invoiceguard_history")||"{}")}catch{return {}}}
function saveHistory(rows){const h=history();rows.forEach(r=>{const no=(r.invoice_number||"").trim(),vendor=(r.vendor||"").trim();if(no&&vendor)h[duplicateKey(vendor,no)]={vendor,no,date:r.date||"",total:num(r.total)||0}});const keys=Object.keys(h);if(keys.length>500)keys.slice(0,keys.length-500).forEach(k=>delete h[k]);localStorage.setItem("invoiceguard_history",JSON.stringify(h))}
function audit(rows){const seen=new Map(),past=priorHistory,find=[];rows.forEach(r=>{const no=(r.invoice_number||"").trim(),vendor=(r.vendor||"").trim(),total=num(r.total),sub=num(r.subtotal),tax=num(r.tax);const add=(severity,msg)=>find.push({row:r._row,no:no||"—",vendor:vendor||"—",date:r.date||"",severity,msg,total:Number.isFinite(total)?total:0,currency:r.currency||""});if(!no)add("High","Missing invoice number");if(!vendor)add("High","Missing vendor");if(!r.date)add("Medium","Missing invoice date");else{const d=new Date(r.date);if(Number.isNaN(d.getTime()))add("Medium","Invoice date is not valid");else{const tomorrow=new Date();tomorrow.setHours(23,59,59,999);tomorrow.setDate(tomorrow.getDate()+1);if(d>tomorrow)add("Medium","Invoice date is unexpectedly in the future")}}if(!r.currency)add("Medium","Missing currency");else if(rules.allowedCurrencies.length&&!rules.allowedCurrencies.includes(String(r.currency).trim().toUpperCase()))add("Medium","Currency is not on the allowed list");if(!Number.isFinite(total)||total<=0)add("High","Invalid or non-positive total");if(Number.isFinite(sub)&&Number.isFinite(tax)&&Number.isFinite(total)&&Math.abs((sub+tax)-total)>rules.tolerance)add("High","Subtotal + tax does not match total");if(Number.isFinite(sub)&&sub>0&&Number.isFinite(tax)){const rate=tax/sub*100;if(rate<0)add("High","Negative tax amount");else if(rate>rules.maxTaxRate)add("Medium","Tax rate "+rate.toFixed(1)+"% exceeds configured maximum")}if(no&&vendor){const key=duplicateKey(vendor,no);if(past[key])add("High","Invoice also appeared in a previous audit");if(seen.has(key)){add("High","Possible duplicate invoice number in this file");const first=seen.get(key);if(!first.flagged){find.push({row:first.row,no:first.no,vendor:first.vendor,date:first.date,severity:"High",msg:"Possible duplicate invoice number in this file",total:first.total,currency:first.currency});first.flagged=true}}else seen.set(key,{row:r._row,no,vendor,date:r.date||"",total:Number.isFinite(total)?total:0,currency:r.currency||"",flagged:false})}});return find}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function riskText(findings){const seen=new Set(),totals={};findings.filter(x=>x.severity==="High").forEach(x=>{const key=[x.row,x.no,x.vendor].join("|");if(seen.has(key))return;seen.add(key);const c=String(x.currency||"UNKNOWN").trim().toUpperCase()||"UNKNOWN";totals[c]=(totals[c]||0)+(Number.isFinite(x.total)?x.total:0)});const entries=Object.entries(totals).filter(([,v])=>v!==0);return entries.length?entries.map(([c,v])=>c+" "+new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(v)).join(" · "):"0"}
function render(rows){currentRows=rows;current=audit(rows);$("results").classList.remove("hidden");$("count").textContent=rows.length;$("issues").textContent=current.length;$("risk").textContent=riskText(current);$("findings").innerHTML=current.length?current.map(x=>`<tr><td>${x.row}</td><td>${esc(x.no)}</td><td>${esc(x.vendor)}</td><td class="sev-${x.severity.toLowerCase()}">${x.severity}</td><td>${esc(x.msg)}</td><td>${esc(x.currency)} ${x.total.toLocaleString()}</td></tr>`).join(""):`<tr><td colspan="6">No issues found in the supported checks.</td></tr>`;saveHistory(rows);location.hash="results"}
function load(text){rawText=text;priorHistory=history();const rows=parseCSV(text);if(!rows.length){alert("No invoice rows found. Please check the CSV.");return}render(rows)}
$("applyRules").addEventListener("click",()=>{const tolerance=Math.max(0,Number($("tolerance").value)||0),maxTaxRate=Math.max(0,Number($("maxTaxRate").value)||0),allowedCurrencies=$("allowedCurrencies").value.split(",").map(x=>x.trim().toUpperCase()).filter(Boolean);rules={tolerance,maxTaxRate,allowedCurrencies};localStorage.setItem("invoiceguard_rules",JSON.stringify(rules));$("ruleStatus").textContent="Rules saved locally.";if(currentRows.length){current=audit(currentRows);$("issues").textContent=current.length;$("risk").textContent=riskText(current);$("findings").innerHTML=current.length?current.map(x=>`<tr><td>${x.row}</td><td>${esc(x.no)}</td><td>${esc(x.vendor)}</td><td class="sev-${x.severity.toLowerCase()}">${x.severity}</td><td>${esc(x.msg)}</td><td>${esc(x.currency)} ${x.total.toLocaleString()}</td></tr>`).join(""):`<tr><td colspan="6">No issues found in the supported checks.</td></tr>`;}});
syncRuleInputs();
$("applyMapping").addEventListener("click",()=>{document.querySelectorAll("#mappingFields select").forEach(s=>{if(s.value)customMap[s.dataset.col]=s.value});if(rawText)load(rawText)});
$("file").addEventListener("change",e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader;r.onload=()=>load(r.result);r.readAsText(f)});
$("demo").addEventListener("click",()=>load("Invoice No,Supplier,Invoice Date,Net Amount,VAT,Amount Due,Currency Code\nINV-101,Acme Ltd,2026-09-01,1000,100,1100,USD\nINV-101,Acme Ltd,2026-09-02,1000,100,1100,USD\nINV-102,,2026-09-03,500,50,600,USD\n,North Star,,250,25,-275,"));
$("clearHistory").addEventListener("click",()=>{localStorage.removeItem("invoiceguard_history");$("historyStatus").textContent="Local audit history cleared."});
$("downloadClean").addEventListener("click",()=>{const q=s=>'"'+String(s??"").replaceAll('"','""')+'"';const head=["invoice_number","vendor","date","subtotal","tax","total","currency"];const csv=[head.join(","),...currentRows.map(r=>head.map(k=>q(r[k]||"")).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="invoiceguard-clean-invoices.csv";a.click();URL.revokeObjectURL(a.href)});
$("download").addEventListener("click",()=>{const q=s=>'"'+String(s).replaceAll('"','""')+'"';const csv=["row,invoice,vendor,date,severity,finding,total,currency",...current.map(x=>[x.row,x.no,x.vendor,x.date||"",x.severity,x.msg,x.total,x.currency].map(q).join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download="invoiceguard-findings.csv";a.click();URL.revokeObjectURL(a.href)});
$("downloadSummary").addEventListener("click",()=>{const high=current.filter(x=>x.severity==="High").length,medium=current.filter(x=>x.severity==="Medium").length;const unique=new Set(current.filter(x=>x.severity==="High").map(x=>[x.row,x.no,x.vendor].join("|"))).size;const lines=["INVOICEGUARD AUDIT SUMMARY","Generated: "+new Date().toLocaleString(),"Invoices reviewed: "+currentRows.length,"Findings: "+current.length+" ("+high+" high, "+medium+" medium)","Invoices requiring attention: "+unique,"At-risk value: "+riskText(current),"","RECOMMENDATION",high?"Hold flagged invoices for review before payment.":"No high-severity issues detected by the supported checks.","","HIGH-SEVERITY FINDINGS",...(current.filter(x=>x.severity==="High").map(x=>"Row "+x.row+" | "+x.vendor+" | "+x.no+" | "+(x.date||"no date")+" | "+x.msg+" | "+x.currency+" "+x.total)||["None"])];const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([lines.join("\n")],{type:"text/plain"}));a.download="invoiceguard-audit-summary.txt";a.click();URL.revokeObjectURL(a.href)});
