(()=>{
const copy={
en:{title:"INVOICEGUARD PAYMENT REVIEW",generated:"Generated",source:"Source",settings:"Audit settings",tolerance:"Amount tolerance",tax:"Maximum tax rate",currencies:"Allowed currencies",required:"Required fields",reviewed:"Invoices reviewed",findings:"Findings",attention:"Invoices requiring attention",risk:"At-risk value",decision:"Payment decision",hold:"HOLD PAYMENT",review:"REVIEW BEFORE PAYMENT",ready:"READY FOR APPROVAL",action:"Recommended action",holdAction:"Resolve all high-severity findings before releasing payment.",reviewAction:"Have an accountant verify the review findings before approval.",readyAction:"No supported checks found an exception. Continue with your normal approval controls.",high:"PAYMENT-BLOCKING FINDINGS",medium:"REVIEW FINDINGS",row:"Row",noneHigh:"No payment-blocking findings.",noneMedium:"No review findings.",sample:"InvoiceGuard sample audit"},
ru:{title:"INVOICEGUARD — ПРОВЕРКА ПЕРЕД ОПЛАТОЙ",generated:"Сформировано",source:"Источник",settings:"Настройки аудита",tolerance:"Допуск суммы",tax:"Максимальная ставка налога",currencies:"Разрешённые валюты",required:"Обязательные поля",reviewed:"Проверено счетов",findings:"Замечания",attention:"Счета, требующие внимания",risk:"Сумма под риском",decision:"Решение по оплате",hold:"ОСТАНОВИТЬ ОПЛАТУ",review:"ПРОВЕРИТЬ ДО ОПЛАТЫ",ready:"ГОТОВО К СОГЛАСОВАНИЮ",action:"Рекомендуемое действие",holdAction:"Устраните все критические замечания до проведения оплаты.",reviewAction:"Попросите бухгалтера проверить замечания перед согласованием.",readyAction:"Поддерживаемые проверки не выявили исключений. Продолжайте стандартный процесс согласования.",high:"БЛОКИРУЮЩИЕ ОПЛАТУ ЗАМЕЧАНИЯ",medium:"ЗАМЕЧАНИЯ ДЛЯ ПРОВЕРКИ",row:"Строка",noneHigh:"Блокирующих оплату замечаний нет.",noneMedium:"Замечаний для проверки нет.",sample:"Демонстрационный аудит InvoiceGuard"},
uz:{title:"INVOICEGUARD — TO‘LOVDAN OLDINGI TEKSHIRUV",generated:"Yaratildi",source:"Manba",settings:"Audit sozlamalari",tolerance:"Summa og‘ishi",tax:"Maksimal soliq stavkasi",currencies:"Ruxsat etilgan valyutalar",required:"Majburiy maydonlar",reviewed:"Tekshirilgan hisoblar",findings:"Topilmalar",attention:"E’tibor talab qiladigan hisoblar",risk:"Xavf ostidagi qiymat",decision:"To‘lov qarori",hold:"TO‘LOVNI TO‘XTATING",review:"TO‘LOVDAN OLDIN TEKSHIRING",ready:"TASDIQLASHGA TAYYOR",action:"Tavsiya etilgan amal",holdAction:"To‘lovni amalga oshirishdan oldin barcha yuqori darajali topilmalarni bartaraf eting.",reviewAction:"Tasdiqlashdan oldin buxgalter tekshiruv topilmalarini ko‘rib chiqsin.",readyAction:"Qo‘llab-quvvatlanadigan tekshiruvlarda istisno topilmadi. Odatdagi tasdiqlash nazoratlarini davom ettiring.",high:"TO‘LOVNI BLOKLOVCHI TOPILMALAR",medium:"TEKSHIRISH UCHUN TOPILMALAR",row:"Qator",noneHigh:"To‘lovni bloklovchi topilmalar yo‘q.",noneMedium:"Tekshirish uchun topilmalar yo‘q.",sample:"InvoiceGuard namuna auditi"},
es:{title:"INVOICEGUARD — REVISIÓN PREVIA AL PAGO",generated:"Generado",source:"Origen",settings:"Configuración de auditoría",tolerance:"Tolerancia de importe",tax:"Tasa máxima de impuesto",currencies:"Monedas permitidas",required:"Campos obligatorios",reviewed:"Facturas revisadas",findings:"Hallazgos",attention:"Facturas que requieren atención",risk:"Valor en riesgo",decision:"Decisión de pago",hold:"RETENER PAGO",review:"REVISAR ANTES DE PAGAR",ready:"LISTO PARA APROBACIÓN",action:"Acción recomendada",holdAction:"Resuelve todos los hallazgos de alta severidad antes de liberar el pago.",reviewAction:"Haz que contabilidad verifique los hallazgos de revisión antes de aprobar.",readyAction:"Las comprobaciones compatibles no encontraron excepciones. Continúa con los controles habituales de aprobación.",high:"HALLAZGOS QUE BLOQUEAN EL PAGO",medium:"HALLAZGOS PARA REVISIÓN",row:"Fila",noneHigh:"No hay hallazgos que bloqueen el pago.",noneMedium:"No hay hallazgos para revisión.",sample:"Auditoría de ejemplo de InvoiceGuard"},
de:{title:"INVOICEGUARD — ZAHLUNGSPRÜFUNG",generated:"Erstellt",source:"Quelle",settings:"Prüfeinstellungen",tolerance:"Betragstoleranz",tax:"Maximaler Steuersatz",currencies:"Erlaubte Währungen",required:"Pflichtfelder",reviewed:"Geprüfte Rechnungen",findings:"Feststellungen",attention:"Rechnungen mit Handlungsbedarf",risk:"Gefährdeter Wert",decision:"Zahlungsentscheidung",hold:"ZAHLUNG STOPPEN",review:"VOR ZAHLUNG PRÜFEN",ready:"BEREIT ZUR FREIGABE",action:"Empfohlene Maßnahme",holdAction:"Beheben Sie alle Feststellungen mit hoher Schwere, bevor die Zahlung freigegeben wird.",reviewAction:"Lassen Sie die Prüffeststellungen vor der Freigabe durch die Buchhaltung verifizieren.",readyAction:"Die unterstützten Prüfungen haben keine Ausnahme gefunden. Fahren Sie mit Ihren üblichen Freigabekontrollen fort.",high:"ZAHLUNGSBLOCKIERENDE FESTSTELLUNGEN",medium:"FESTSTELLUNGEN ZUR PRÜFUNG",row:"Zeile",noneHigh:"Keine zahlungsblockierenden Feststellungen.",noneMedium:"Keine Feststellungen zur Prüfung.",sample:"InvoiceGuard-Beispielprüfung"},
fr:{title:"INVOICEGUARD — REVUE AVANT PAIEMENT",generated:"Généré",source:"Source",settings:"Paramètres d’audit",tolerance:"Tolérance de montant",tax:"Taux de taxe maximal",currencies:"Devises autorisées",required:"Champs obligatoires",reviewed:"Factures examinées",findings:"Constats",attention:"Factures nécessitant une attention",risk:"Valeur à risque",decision:"Décision de paiement",hold:"SUSPENDRE LE PAIEMENT",review:"VÉRIFIER AVANT PAIEMENT",ready:"PRÊT POUR APPROBATION",action:"Action recommandée",holdAction:"Résolvez tous les constats de sévérité élevée avant de libérer le paiement.",reviewAction:"Faites vérifier les constats par la comptabilité avant approbation.",readyAction:"Les contrôles pris en charge n’ont détecté aucune exception. Poursuivez vos contrôles d’approbation habituels.",high:"CONSTATS BLOQUANT LE PAIEMENT",medium:"CONSTATS À VÉRIFIER",row:"Ligne",noneHigh:"Aucun constat bloquant le paiement.",noneMedium:"Aucun constat à vérifier.",sample:"Audit d’exemple InvoiceGuard"},
pt:{title:"INVOICEGUARD — REVISÃO ANTES DO PAGAMENTO",generated:"Gerado",source:"Origem",settings:"Definições da auditoria",tolerance:"Tolerância de valor",tax:"Taxa máxima de imposto",currencies:"Moedas permitidas",required:"Campos obrigatórios",reviewed:"Faturas revisadas",findings:"Achados",attention:"Faturas que exigem atenção",risk:"Valor em risco",decision:"Decisão de pagamento",hold:"SUSPENDER PAGAMENTO",review:"REVER ANTES DE PAGAR",ready:"PRONTO PARA APROVAÇÃO",action:"Ação recomendada",holdAction:"Resolva todos os achados de alta severidade antes de liberar o pagamento.",reviewAction:"Peça à contabilidade para verificar os achados de revisão antes da aprovação.",readyAction:"As verificações suportadas não encontraram exceções. Continue com os seus controlos habituais de aprovação.",high:"ACHADOS QUE BLOQUEIAM O PAGAMENTO",medium:"ACHADOS PARA REVISÃO",row:"Linha",noneHigh:"Nenhum achado bloqueia o pagamento.",noneMedium:"Nenhum achado para revisão.",sample:"Auditoria de exemplo InvoiceGuard"}
};
const locale={en:"en-US",ru:"ru-RU",uz:"uz-UZ",es:"es-ES",de:"de-DE",fr:"fr-FR",pt:"pt-PT"};
function activeLang(){return window.invoiceGuardI18n?.lang||document.getElementById("language")?.value||"en"}
function downloadSummary(e){
 e.preventDefault();e.stopImmediatePropagation();
 const l=activeLang(),t=copy[l]||copy.en;
 const domRows=[...document.querySelectorAll("#findings tr")];
 const rows=domRows.map(tr=>({cells:[...tr.cells].map(td=>td.textContent.trim()),high:!!tr.querySelector(".sev-high"),medium:!!tr.querySelector(".sev-medium")})).filter(r=>r.cells.length>=6);
 const highRows=rows.filter(r=>r.high),mediumRows=rows.filter(r=>r.medium);
 const attention=new Set(rows.filter(r=>r.high||r.medium).map(r=>r.cells[0]+"|"+r.cells[1]+"|"+r.cells[2])).size;
 const count=document.getElementById("count")?.textContent?.trim()||"0",issues=document.getElementById("issues")?.textContent?.trim()||"0",risk=document.getElementById("risk")?.textContent?.trim()||"0";
 const decision=highRows.length?t.hold:(mediumRows.length?t.review:t.ready),action=highRows.length?t.holdAction:(mediumRows.length?t.reviewAction:t.readyAction);
 const source=document.documentElement.dataset.auditSource||document.getElementById("file")?.files?.[0]?.name||t.sample;
 const tolerance=document.getElementById("tolerance")?.value||"0.02",tax=document.getElementById("maxTaxRate")?.value||"30",currencies=document.getElementById("allowedCurrencies")?.value||"";
 const required=[...document.querySelectorAll("[data-required-field]:checked")].map(x=>document.querySelector(`[data-required-label="${x.dataset.requiredField}"]`)?.textContent?.trim()||x.dataset.requiredField).join(", ")||"—";
 const fmt=r=>`${t.row} ${r.cells[0]} | ${r.cells[2]} | ${r.cells[1]} | ${r.cells[4]} | ${r.cells[5]}`;
 const lines=[t.title,`${t.generated}: ${new Date().toLocaleString(locale[l]||l)}`,`${t.source}: ${source}`,"",t.settings,`${t.tolerance}: ${tolerance}`,`${t.tax}: ${tax}%`,`${t.currencies}: ${currencies||"—"}`,`${t.required}: ${required}`,"",`${t.decision}: ${decision}`,`${t.action}: ${action}`,"",`${t.reviewed}: ${count}`,`${t.findings}: ${issues} (${highRows.length} ${window.invoiceGuardI18n?.t?.("high")||"High"}, ${mediumRows.length} ${window.invoiceGuardI18n?.t?.("medium")||"Medium"})`,`${t.attention}: ${attention}`,`${t.risk}: ${risk}`,"",t.high,...(highRows.length?highRows.map(fmt):[t.noneHigh]),"",t.medium,...(mediumRows.length?mediumRows.map(fmt):[t.noneMedium])];
 const blob=new Blob(["\uFEFF"+lines.join("\n")],{type:"text/plain;charset=utf-8"});
 const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`invoiceguard-payment-review-${l}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0);
}
document.getElementById("downloadSummary")?.addEventListener("click",downloadSummary,true);
})();