(()=>{
  const extra={
    en:{trustTitle:'Built for a safer payment review',trustLocalTitle:'Your invoice data stays local',trustLocalBody:'CSV audits run in your browser. InvoiceGuard does not upload invoice rows to a server for the audit.',trustDecisionTitle:'You stay in control',trustDecisionBody:'InvoiceGuard highlights evidence and review items. It does not approve payments or replace your accounting controls.',faqTitle:'Frequently asked questions',faqFileQ:'What files can I audit?',faqFileA:'The current MVP audits CSV invoice exports. PDF and image ingestion are not part of the current product.',faqStoreQ:'Do you store my invoices?',faqStoreA:'Audit processing is browser-local. Cross-upload duplicate history is stored locally in this browser and can be cleared at any time.',faqPayQ:'Does InvoiceGuard make payment decisions?',faqPayA:'No. Findings are decision support for your team. Payment approval remains with your business and its accounting controls.'},
    ru:{trustTitle:'Для более безопасной проверки перед оплатой',trustLocalTitle:'Данные счетов остаются локально',trustLocalBody:'CSV проверяется в вашем браузере. InvoiceGuard не отправляет строки счетов на сервер для проведения аудита.',trustDecisionTitle:'Решение остаётся за вами',trustDecisionBody:'InvoiceGuard показывает факты и пункты для проверки. Он не согласовывает платежи и не заменяет ваши бухгалтерские контроли.',faqTitle:'Частые вопросы',faqFileQ:'Какие файлы можно проверять?',faqFileA:'Текущий MVP проверяет CSV-выгрузки счетов. PDF и изображения пока не поддерживаются.',faqStoreQ:'Вы храните мои счета?',faqStoreA:'Проверка выполняется локально в браузере. История дублей между загрузками хранится только в этом браузере и может быть очищена в любой момент.',faqPayQ:'InvoiceGuard принимает решение об оплате?',faqPayA:'Нет. Результаты помогают вашей команде принять решение. Согласование оплаты остаётся за вашей компанией и её бухгалтерскими контролями.'},
    uz:{trustTitle:"To‘lovdan oldingi xavfsizroq tekshiruv uchun",trustLocalTitle:"Hisob ma’lumotlari lokal qoladi",trustLocalBody:"CSV auditi brauzeringizda ishlaydi. InvoiceGuard audit uchun hisob qatorlarini serverga yuklamaydi.",trustDecisionTitle:"Nazorat sizda qoladi",trustDecisionBody:"InvoiceGuard dalillar va tekshirilishi kerak bo‘lgan bandlarni ko‘rsatadi. U to‘lovni tasdiqlamaydi va buxgalteriya nazoratlaringizni almashtirmaydi.",faqTitle:"Ko‘p so‘raladigan savollar",faqFileQ:"Qaysi fayllarni tekshirish mumkin?",faqFileA:"Hozirgi MVP CSV hisob eksportlarini tekshiradi. PDF va rasm fayllari hozircha qo‘llab-quvvatlanmaydi.",faqStoreQ:"Hisoblarim saqlanadimi?",faqStoreA:"Audit brauzerda lokal bajariladi. Yuklashlar orasidagi dublikat tarixi faqat shu brauzerda saqlanadi va istalgan payt tozalanishi mumkin.",faqPayQ:"InvoiceGuard to‘lov qarorini qabul qiladimi?",faqPayA:"Yo‘q. Natijalar jamoangizga qaror qabul qilishda yordam beradi. To‘lovni tasdiqlash biznesingiz va uning buxgalteriya nazoratlarida qoladi."},
    es:{trustTitle:'Creado para una revisión de pago más segura',trustLocalTitle:'Los datos de tus facturas permanecen locales',trustLocalBody:'Las auditorías CSV se ejecutan en tu navegador. InvoiceGuard no sube las filas de tus facturas a un servidor para auditarlas.',trustDecisionTitle:'Tú mantienes el control',trustDecisionBody:'InvoiceGuard muestra evidencias y puntos a revisar. No aprueba pagos ni sustituye tus controles contables.',faqTitle:'Preguntas frecuentes',faqFileQ:'¿Qué archivos puedo auditar?',faqFileA:'El MVP actual audita exportaciones CSV de facturas. La carga de PDF e imágenes no forma parte del producto actual.',faqStoreQ:'¿Guardan mis facturas?',faqStoreA:'La auditoría se procesa localmente en el navegador. El historial de duplicados entre cargas se guarda solo en este navegador y puede borrarse en cualquier momento.',faqPayQ:'¿InvoiceGuard toma decisiones de pago?',faqPayA:'No. Los hallazgos sirven de apoyo a tu equipo. La aprobación del pago sigue siendo responsabilidad de tu empresa y sus controles contables.'},
    de:{trustTitle:'Für eine sicherere Prüfung vor der Zahlung',trustLocalTitle:'Deine Rechnungsdaten bleiben lokal',trustLocalBody:'CSV-Prüfungen laufen in deinem Browser. InvoiceGuard lädt Rechnungszeilen für die Prüfung nicht auf einen Server hoch.',trustDecisionTitle:'Du behältst die Kontrolle',trustDecisionBody:'InvoiceGuard zeigt Nachweise und Prüfpunkte. Es genehmigt keine Zahlungen und ersetzt keine Buchhaltungskontrollen.',faqTitle:'Häufige Fragen',faqFileQ:'Welche Dateien kann ich prüfen?',faqFileA:'Das aktuelle MVP prüft CSV-Rechnungsexporte. PDF- und Bildimport gehören derzeit nicht zum Produkt.',faqStoreQ:'Speichert ihr meine Rechnungen?',faqStoreA:'Die Prüfung erfolgt lokal im Browser. Der Verlauf für Duplikate zwischen Uploads wird nur in diesem Browser gespeichert und kann jederzeit gelöscht werden.',faqPayQ:'Trifft InvoiceGuard Zahlungsentscheidungen?',faqPayA:'Nein. Die Befunde unterstützen dein Team bei der Entscheidung. Die Zahlungsfreigabe bleibt bei deinem Unternehmen und seinen Buchhaltungskontrollen.'},
    fr:{trustTitle:'Conçu pour sécuriser la vérification avant paiement',trustLocalTitle:'Vos données de facture restent locales',trustLocalBody:'Les audits CSV s’exécutent dans votre navigateur. InvoiceGuard n’envoie pas les lignes de facture vers un serveur pour l’audit.',trustDecisionTitle:'Vous gardez le contrôle',trustDecisionBody:'InvoiceGuard présente les éléments probants et les points à vérifier. Il n’approuve aucun paiement et ne remplace pas vos contrôles comptables.',faqTitle:'Questions fréquentes',faqFileQ:'Quels fichiers puis-je auditer ?',faqFileA:'Le MVP actuel audite les exports CSV de factures. L’import de PDF et d’images ne fait pas partie du produit actuel.',faqStoreQ:'Stockez-vous mes factures ?',faqStoreA:'L’audit est traité localement dans le navigateur. L’historique des doublons entre imports est conservé uniquement dans ce navigateur et peut être effacé à tout moment.',faqPayQ:'InvoiceGuard prend-il des décisions de paiement ?',faqPayA:'Non. Les résultats aident votre équipe à décider. L’approbation du paiement reste sous la responsabilité de votre entreprise et de ses contrôles comptables.'},
    pt:{trustTitle:'Criado para uma revisão de pagamento mais segura',trustLocalTitle:'Os dados das suas faturas ficam locais',trustLocalBody:'As auditorias de CSV são executadas no navegador. O InvoiceGuard não envia as linhas das faturas a um servidor para realizar a auditoria.',trustDecisionTitle:'Você mantém o controle',trustDecisionBody:'O InvoiceGuard apresenta evidências e itens para revisão. Ele não aprova pagamentos nem substitui seus controles contábeis.',faqTitle:'Perguntas frequentes',faqFileQ:'Quais arquivos posso auditar?',faqFileA:'O MVP atual audita exportações CSV de faturas. A importação de PDF e imagens não faz parte do produto atual.',faqStoreQ:'Vocês armazenam minhas faturas?',faqStoreA:'A auditoria é processada localmente no navegador. O histórico de duplicatas entre envios fica somente neste navegador e pode ser apagado a qualquer momento.',faqPayQ:'O InvoiceGuard toma decisões de pagamento?',faqPayA:'Não. Os resultados apoiam a decisão da sua equipe. A aprovação do pagamento continua sob responsabilidade da sua empresa e de seus controles contábeis.'}
  };
  const i18n=window.invoiceGuardI18n;
  if(!i18n||!i18n.dict)return;
  Object.entries(extra).forEach(([lang,strings])=>Object.assign(i18n.dict[lang],strings));
})();
